import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>{process.env.NEXT_PUBLIC_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Link to <Link href={`${process.env.NEXT_PUBLIC_API_URL_LOCAL}/swagger-ui.html`} target='_blank' >API Documentation</Link></h1>
      </main>
    </>
  )
}
